#Added the configmap that connect the prometheus to grafana 
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: amazona
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-service.amazona.svc.cluster.local:9090/prometheus
        access: proxy
        isDefault: true
---
#Setup for grafana deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: amazona
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:10.0.0
        ports:
        - containerPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "admin"
        volumeMounts:
        - name: grafana-datasources         
          mountPath: /etc/grafana/provisioning/datasources
      volumes:
      - name: grafana-datasources
        configMap:
          name: grafana-datasources

---
#The grafana service setup 
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: amazona
spec:
  selector:
    app: grafana
  ports:
  - name: grafana
    port: 3000
    targetPort: 3000
  type: ClusterIP

