apiVersion: v1
kind: Secret
metadata:
  name: amazona-secrets
  namespace: amazona
  labels:
    app: amazona
    component: secrets
    managed-by: configuration-team
type: Opaque
stringData:
  aws-access-key-id: "${AWS_ACCESS_KEY}"
  aws-secret-access-key: "${AWS_SECRET_KEY}"

  mongo-root-username: "${DB_USER}"
  mongo-root-password: "${DB_PASS}"

  jwt-secret: "${JWT_TOKEN}"

